// Upcoming Changes
// Game: Overwatch 2
// Season: 9

// New updates can be found here ahead of release on the API. Asterisks(*) mark updates that arent finalized. 

/*
# D.va
Real Name:
Hana Song (송하나)
Aliases: []
Status: null
Birth:
June 22nd

Age:
21 (Overwatch 2)
19 (Overwatch)

Nationality:
South Korea Korean

Occupation:
Professional gamer (formerly)
Mech pilot
Actress

Base:
MEKA Base, Busan, South Korea (formerly)
'Watchpoint: Gibraltar'

Affiliation:
Mobile Exo-Force of the Korean Army (MEKA) (South Korean Army)
Overwatch

Voice:
Charlet Chung (English)

Role: Tank

Health:
225 (Open queue)
375 (Role queue)
175 (Pilot Form, tank passive is ignored)
350 (6v6)

Armor:
325
0 (Pilot Form)
300 (6v6)



*/


const heroData = [
  {
    name: "D.Va",
    realName: "Hana Song (송하나)",
    type: "tank",
    counters: {
      Ana: "+",
      Ashe: "+",
      Bastion: "+",
      Brigitte: "-",
      Doomfist: "-",
      Freja: "+",
      // Genji: "+",
      Hanzo: "++",
      Junkrat: "-",
      Ilari: "+",
      Cassidy: "+",
      Mauga: "+",
      Mei: "-",
      Mercy: "++",
      Moira: "+",
      Pharah: "+",
      Reaper: "+",
      Sombra: "-",
      Symmetra: "-",
      Widowmaker: "++",
      Zarya: "--"
    }, 
    archetype: ["First Responder"],
    difficulty: 2,
    skill: 2,
    role: "Tank",
    health: { openQueue: 225, roleQueue: 375, pilotForm: 175, sixVSix: 350 },
    armor: { openQueue: 325, roleQueue: 325, pilotForm: 0, sixVSix: 300 },
    shields: { openQueue: 0, roleQueue: 0, pilotForm: 0, sixVSix: 0 },
    birth: "June 22",
    age: 21,
    ages: { Overwatch: 19, "Overwatch 2": 21 },
    nationality: "Korean",
    occupation: ["Professional gamer (formerly)", "Mech pilot", "Actress"],
    base: [ "MEKA Base, Busan, South Korea (formerly)", "Watchpoint: Gibraltar"],
    affiliation: ["Mobile Exo-Force of the Korean Army (MEKA)", "South Korean Army", "Overwatch"],
    voice: "Charlet Chung (English)",
    quotes: ["Time to save the world? Game on!"]
  },
  {
    name: "Doomfist",
    realName: "Akande Ogundimu",
    type: "tank",
    counters: {
      Ashe: "-",
      Dva: "+",
      Mauga: "-",
      Mei: "-", 
      Orisa: "--",
      Pharah: "--",
      Reaper: "-",
      Roadhog: "-",
      Soldier76: "-",
      Sombra: "--"
    },
    archetype: ["Initiator"],
    difficulty: 3,
    skill: 3,
    role: "Tank",
    health: { openQueue: 375, roleQueue: 525, sixVSix: 425 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: "Alive",
    birth: "May 25",
    age: 47,
    ages: { Overwatch: 45, "Overwatch 2": 47 },
    nationality: "Nigerian",
    occupation: ["Martial artist (formerly)", "Mercenary", "CEO", "Talon council member"],
    base: [ "Oyo, Nigeria (formerly)", "Rome, Italy"],
    affiliation: ["Ogundimu Synergies Inc. (formerly)", "Talon"],
    relations: ["Akinjide Adeyemi (mentor)"],
    voice: "Sahr Ngaujah (English)",
    quotes: ["Our future will be forged in conflict."]
  },
  {
    name: "Hazard",
    realName: "Findlay Docherty",
    type: "tank",
    counters: {
      Ana: "-",
      Ashe: "-",
      Bastion: "-",
      Cassidy: "-",
      //Dva: "-",
      Echo: "-",
      //Genji: "+",
      Mauga: "-",
      //Mei: "-*",
      Orisa: "-",
      Roadhog: "--",
      Pharah: "-",
      //Sigma: "+*",
      Sombra: "-",
      // Tracer: "+",
      //Widomaker:"-",
      // WreckingBall: "+",
      Zenyatta: "-*",
    }, 
    archetype: ["Initiator", "Scrapper"],
    difficulty: null,
    skill: null,
    role: "Tank",
    health: { openQueue: 275, roleQueue: 425 },
    armor: { openQueue: 225, roleQueue: 225 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: "Active",
    birth: "November 11",
    age: 24,
    ages: { "Overwatch 2": 24 },
    nationality: "Scottish",
    occupation: ["Soldier (formerly)", "Punk rocker"],
    base: [ "Glasgow, Scotland (formerly)", "Unknown"],
    affiliation: ["British military (formerly)", "Phreaks"],
    relations: ["Susannah (partner)"],
    voice: "Conor McLeod (English)",
  },
  {
    name: "Junker Queen",
    realName: "Odessa \"Dez\" Stone",
    type: "tank",
    counters: {
      Ana: "+",
      Bastion: "--",
      Reaper: "-",
      Mei: "--",
      Orisa: "-",
      WreckingBall: "++", // new
      Zenyatta: "-"
    },
    archetype: ["Damage Heavy"],
    difficulty: null,
    skill: null,
    role: "Tank",
    health: { openQueue: 375, roleQueue: 525, sixVSix: 425 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: "Active",
    birth: "June 14",
    age: 31,
    ages: { "Overwatch 2": 31 },
    nationality: "Australian",
    occupation: ["Gladiator champion (formerly)", "Ruler of Junkertown"],
    base: [ "Junkertown, Australia"],
    affiliation: ["Wastelanders (temporarily)", "Junkers"],
    relations: ["Stone (father)", "unnamed mother", "5 siblings"],
    voice: "Leah de Niese (English)",
    quotes: ["My throne is where I say it is."]
  },
  {
    name: "Mauga",
    realName: "Maugaloa Malosi",
    type: "tank",
    counters: {
      Ana: "-",
      Dva: "-",
      Doomfist: "+", 
      Mei: "-",
      Roadhog: "++", 
      Orisa: "-", 
      Sigma: "-",
      WreckingBall: "+",
    },
    archetype: ["Damage Heavy"],
    difficulty: null,
    skill: null,
    role: "Tank",
    health: { openQueue: 425, roleQueue: 575, sixVSix: 450 },
    armor: { openQueue: 150, roleQueue: 150, sixVSix: 100 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: "Active",
    birth: "August 19",
    age: 37,
    ages: { "Overwatch 2": 37 },
    nationality: "Samoan",
    occupation: ["Mercenary"],
    base: [ "Apia, Samoa"],
    affiliation: ["Deepsea Raiders (formerly)", "Talon"],
    relations: ["Malosi (father)"],
    voice: "John Tui (English)",
    quotes: ["A gun in each hand and a smile on my face!"]
  },
  {
    name: "Orisa",
    type: "tank",
    counters: {
      Ashe: "+",
      Doomfist: "++",
      //Genji: "-",
      Freja: "-*",
      Hanzo: "-",
      JunkerQueen: "+",
      Junkrat: "-",
      Mauga: "+", // new
      Moira: "-",
      Ramattra: "+",
      Reaper: "-",
      Sigma: "-", 
      Torbjorn: "+",
      Widowmaker: "-",
      Zarya: "-",
      Zenyatta: "-"
    },
    archetype: ["Anchor"],
    difficulty: 2,
    skill: 2,
    role: "Tank",
    health: { openQueue: 150, roleQueue: 300, sixVSix: 250 },
    armor: { openQueue: 300, roleQueue: 300, sixVSix: 250 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: "Active",
    birth: "May 9",
    age: 1,
    nationality: "Numbanian",
    occupation: ["Guardian robot"],
    base: [ "Numbani (formerly)", "Watchpoint: Gibraltar"],
    affiliation: ["Numbani", "Overwatch"],
    relations: ["Efi Oladele (creator)"],
    voice: "Cherrelle Skeete (English)",
    quotes: ["Only in unity will we find strength."]
  },

  {
    name: "Ramattra",
    type: "tank",
    counters: {
      Ashe: "-",
      //Genji: "+",
      Kiriko: "-",
      Orisa: "-",
      Roadhog: "-",
      Reinhardt: "+",
      //Pharah: "+",
      //Echo: "+",
      //WidowMaker: "-",
      Winston: "+",
      //Tracer: "+",
      Zenyatta: "-",
    },
    archetype: ["Anchor"],
    difficulty: 3,
    skill: 3,
    role: "Tank",
    health: { openQueue: 250, roleQueue: 400, sixVSix: 350 },
    armor: { openQueue: 100, roleQueue: 100, sixVSix: 100 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: "Active",
    birth: "March 29",
    age: 28,
    ages: { "Overwatch 2": 28 },
    nationality: "Omnic",
    occupation: ["Military leader (formerly)", "Shambali monk (formerly)", "Leader of Null Sector", "Inventor"],
    base: ["Shambali Monastery, Nepal (formerly)"],
    affiliation: ["Shambali (formerly)", "Null Sector"],
    relations: ["Anubis (creator)"],
    voice: "Ramon Tikaram (English)",
    quotes: ["We will have peace at any cost."]
  },
  {
    name: "Reinhardt",
    realName: "Reinhardt Wilhelm",
    type: "tank",
    counters: {
      Ashe: "+",
      Bastion: "--",
      Brigitte: "-",
      Junkrat: "--",
      Mei: "--",
      Orisa: "-",
      Pharah: "--",
      Ramattra: "-",
      Reaper: "--",
      Sigma: "+",
      Soldier76: "+",
      Sombra: "-",
      Widowmaker: "+", 
      Zenyatta: "-",
    },
    archetype: ["Anchor"],
    difficulty: 1,
    skill: 1,
    role: "Tank",
    health: { openQueue: 250, roleQueue: 400, sixVSix: 325 },
    armor: { openQueue: 300, roleQueue: 300, sixVSix: 225 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: null,
    birth: "June 26",
    age: 63,
    ages: { Overwatch: 61, "Overwatch 2": 63 },
    nationality: "German",
    occupation: ["Crusader (formerly)", "Overwatch agent (formerly)", "Adventurer"],
    base: ["Stuttgart, Germany (formerly)", "Watchpoint: Gibraltar"],
    affiliation: ["German Armed Forces (formerly)", "Crusaders (formerly)", "Overwatch"],
    relations: ["Balderich von Adler (mentor)", "Brigitte Lindholm (squire)"],
    voice: "Darin De Paul (English)",
    quotes: ["Together we will strike them down!"]
  },
  {
    name: "Roadhog",
    realName: "Mako Rutledge",
    type: "tank",
    counters: {
      Ana: "--",
      Baptiste: "+",
      Bastion: "+",
      Doomfist: "+",
      Lucio: "+",
      Cassidy: "+",
      Mauga: "-",
      Mei: "--",
      Mercy: "+",
      Ramattra: "+",
      Reaper: "--",
      Sigma: "-",
      Sombra: "+",
      Widowmaker: "-",
      Winston: "+",
      WreckingBall: "+",
      Zarya: "-",
    },
    archetype: ["Damage Heavy"],
    difficulty: 1,
    skill: 1,
    role: "Tank",
    health: { openQueue: 600, roleQueue: 750, sixVSix: 650 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: "Active",
    birth: "September 12",
    age: 50,
    ages: { Overwatch: 48, "Overwatch 2": 50 },
    nationality: "Australian",
    occupation: ["Enforcer (formerly)", "Bodyguard"],
    base: ["Junkertown, Australia (formerly)"],
    affiliation: ["Australian Liberation Front (formerly)", "Junkers (formerly)", "Wreckers (formerly)"],
    relations: ["Junkrat (partner)"],
    voice: "Josh Petersdorf (English)",
    quotes: ["Apocalypse ain't over."]
  },
  {
    name: "Sigma",
    realName: "Siebren de Kuiper",
    type: "tank",
    counters: {
      Ana: "+",
      Freja: "+",
      Lucio: "-",
      Mauga: "+",
      Orisa: "-",
      Reinhardt: "-",
      Roadhog: "+",
      Soldier76: "+",
      Widowmaker: "+"
    },
    archetype: ["Anchor"],
    difficulty: 3,
    skill: 3,
    role: "Tank",
    health: { openQueue: 200, roleQueue: 350, sixVSix: 200 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 275, roleQueue: 275, sixVSix: 250 },
    status: "Active",
    birth: "March 15",
    age: 64,
    ages: { "Overwatch 2": 64 },
    nationality: "Dutch",
    occupation: ["Scientist (formerly)", "Talon living weapon"],
    base: ["The Hague, Netherlands (formerly)", "International Space Station (formerly)"],
    affiliation: ["Talon"],
    voice: "Boris Hiestand (English)",
    quotes: ["Why seek answers when we do not know the question?"]
  },
  {
    name: "Winston",
    realName: "Winston",
    aliases: ["S. Peaceape"],
    type: "tank",
    counters: {
      Bastion: "-",
      Dva: "++",
      Freja: "+",
      Genji: "++",
      Hanzo: "++",
      Cassidy: "-", 
      Ramattra: "-",
      Reaper: "--",
      Roadhog: "-", 
      Symmetra: "+",
      Widowmaker: "++",
      Zarya: "+", 
      Zenyatta: "++"
    },
    archetype: ["Initiator"],
    difficulty: 2,
    skill: 2,
    role: "Tank",
    health: { openQueue: 275, roleQueue: 425, sixVSix: 350 },
    armor: { openQueue: 200, roleQueue: 200, sixVSix: 200 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: null,
    birth: "June 6",
    age: 31,
    ages: { "Overwatch 2": 31 },
    nationality: null,
    occupation: ["Test subject (formerly)", "Scientist", "Adventurer"],
    base: ["Horizon Lunar Colony (formerly)", "Watchpoint: Gibraltar"],
    affiliation: ["Lucheng Interstellar (formerly)", "Overwatch"],
    relations: null,
    voice: ["Crispin Freeman (English)", "Dee Bradley Baker (English)"],
    quotes: ["A better world is possible today!"]
  },
  {
    name: "Wrecking Ball",
    realName: "Hammond",
    type: "tank",
    counters: {
      Ana: "-",
      Brigitte: "-",
      // Freja: "-*",
      Lucio: "-", 
      Mauga: "-", 
      Mei: "-",
      Moira: "+",
      JunkerQueen: "--",
      Reaper: "-",
      Roadhog: "-",
      Sombra: "--",
      Torbjorn: "-",
      Widowmaker: "+"
    },
    archetype: ["Initiator"],
    difficulty: 3,
    skill: 3,
    role: "Tank",
    health: { openQueue: 300, roleQueue: 450, sixVSix: 500 },
    armor: { openQueue: 175, roleQueue: 175, sixVSix: 100 },
    shields: { openQueue: 150, roleQueue: 150, sixVSix: 0 },
    status: "Active",
    birth: "October 15",
    age: 16,
    ages: { "Overwatch 2": 16 },
    nationality: "Lunar",
    occupation: ["Test subject (formerly)", "Mech pilot", "Mechanic", "Bodyguard"],
    base: ["Horizon Lunar Colony (formerly)", "Junkertown"],
    affiliation: ["Lucheng Interstellar (formerly)", "Junkers"],
    relations: ["Unnamed mother", "Numerous siblings"],
    voice: ["Dee Bradley Baker", "Jonathan Lipow (English)"],
    quotes: ["Weapons operational. Grapples primed. Hamster pumped."]
  },
  {
    name: "Zarya",
    realName: "Aleksandra Zaryanova (Александра Зарянова)",
    aliases: ["Sasha"],
    type: "tank",
    counters: {
      Bastion: "-",
      Dva: "++",
      Genji: "++",
      Junkrat: "+",
      Mei: "+",
      Pharah: "--",
      Sojourn: "+",
      Sombra: "-",
      Reaper: "-",
      Roadhog: "+",
      Torbjorn: "++",
      Winston: "-", // new
      Zenyatta: "-"
    },
    archetype: ["First Responder"],
    difficulty: 3,
    skill: 3,
    role: "Tank",
    health: { openQueue: 175, roleQueue: 325, sixVSix: 225 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 225, roleQueue: 225, sixVSix: 225 },
    status: "Active",
    birth: "December 4",
    age: 30,
    ages: { Overwatch: 28, "Overwatch 2": 30 },
    nationality: "Russian",
    occupation: ["Soldier"],
    base: ["Krasnoyarsk Front, Russia (formerly)", "Novanskoye Forward Base, Siberia, Russia (formerly)", "Watchpoint: Gibraltar"],
    affiliation: ["Russian Defense Forces", "Volskaya Industries (temporarily)", "Overwatch"],
    relations: ["Unnamed father", "Ira Zaryanova (sister)", "Marisha Zaryanova (sister)", "Extended family, including two other siblings or cousins"],
    voice: "Dolya Gavanski (English)",
    quotes: ["We will crush them!"]
  },
  {
    name: "Ashe",
    realName: "Elizabeth Caledonia \"Calamity\" Ashe",
    type: "damage",
    counters: {
      Ana: "-",
      Brigitte: "+",
      Dva: "+",
      Doomfist: "+",
      Echo: "+",
      Freja: "-*",
      Hanzo: "-",
      Junkrat: "+",
      Mei: "+",
      Mercy: "+",
      Orisa: "-",
      Pharah: "++",
      Ramattra: "+",
      Reaper: "+",
      Reinhardt: "-",
      Soldier76: "+",
      Symmetra: "+",
      Widowmaker: "-",
      Winston: "-",
      WreckingBall: "-"
    },
    archetype: ["Anchor", "Sniper"],
    difficulty: 2,
    skill: 2,
    role: "Damage",
    health: { openQueue: 250, roleQueue: 250, sixVSix: 250 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: "Active",
    birth: "October 1",
    age: 41,
    ages: { Overwatch: 39, "Overwatch 2": 41 },
    nationality: "American",
    occupation: ["Thief", "Gang leader"],
    base: ["Deadlock Gorge, Arizona, USA"],
    affiliation: ["Arbalest Arms Company (formerly)", "Deadlock Gang"],
    relations: ["Caledonia Ashe (great-great-great grandmother)", "Mr. Ashe (father)", "Mrs. Ashe (mother)"],
    voice: "Jennifer Hale (English)",
    quotes: ["I'm the last one you'll ever cross."]
  },
  {
    name: "Bastion",
    realName: "Bastion",
    type: "damage",
    counters: {
      Ana: "-",
      Brigitte: "+",
      Dva: "-",
      Echo: "+",
      Genji: "-",
      Hanzo: "--",
      JunkerQueen: "++",
      Junkrat: "-",
      Lucio: "+",
      Reinhardt: "++",
      Roadhog: "-",
      Soldier76: "-",
      Sombra: "-",
      Tracer: "-",
      Widowmaker: "-",
      Winston: "++",
      Zarya: "+"
    },
    archetype: ["Anchor", "Specialist"],
    difficulty: 1,
    skill: 1,
    role: "Damage",
    health: { openQueue: 250, roleQueue: 250, sixVSix: 250 },
    armor: { openQueue: 100, roleQueue: 100, sixVSix: 100 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: null,
    birth: "Unknown",
    age: 32,
    ages: { Overwatch: 30, "Overwatch 2": 32 },
    nationality: "Omnic",
    occupation: ["Battle automaton (formerly)", "Workshop assistant"],
    base: ["Gothenburg, Sweden"],
    affiliation: ["Ironclad Guild"],
    voice: "Chris Metzen (English)",
    quotes: ["(thoughtful beeps)"]
  },
  {
    name: "Cassidy",
    realName: "Cole Cassidy",
    aliases: ["Jesse McCree", "Cass"],
    type: "damage",
    counters: {
      Dva: "-",
      Echo: "+",
      Lucio: "++",
      Mei: "-",
      Mercy: "+",
      Pharah: "++",
      Roadhog: "-",
      Symmetra: "+",
      Tracer: "+",
      Venture: "+", // new
      Widowmaker: "-",
      Winston: "+",
    },
    archetype: ["Anchor"],
    difficulty: 2,
    skill: 2,
    role: "Damage",
    health: { openQueue: 250, roleQueue: 250, sixVSix: 250 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: null,
    birth: "July 31",
    age: 39,
    ages: { Overwatch: 37, "Overwatch 2": 39 },
    nationality: "American",
    occupation: ["Factory worker (formerly)", "Farmhand (formerly)", "Criminal (formerly)", "Overwatch agent", "Bounty hunter", "Mercenary"],
    base: ["Santa Fe, New Mexico, USA (formerly)", "Watchpoint: Gibraltar"],
    affiliation: ["Various employers, including the Ace Valentine megafarm (formerly)", "Deadlock Gang (formerly)", "Overwatch", "Blackwatch (formerly)"],
    voice: "Matthew Mercer (English)",
    quotes: ["Someone needs to fill this saddle."]
  },
  {
    name: "Echo",
    realName: "Echo",
    type: "damage",
    counters: {
      Ana: "-",
      Bastion: "-",
      Baptiste: "-",
      Junkrat: "++",
      Cassidy: "-",
      Reaper: "+",
      Soldier76: "-",
      Sombra: "-",
      Torbjorn: "+",
      Veture: "++",
      Widowmaker: "-"
    },
    archetype: ["Flanker", "Scrapper"],
    difficulty: 2,
    skill: 2,
    role: "Damage",
    health: { openQueue: 150, roleQueue: 150, sixVSix: 150 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 75, roleQueue: 75, sixVSix: 75 },
    status: "Active",
    birth: "February 5",
    age: 14,
    ages: { "Overwatch 2": 14 },
    nationality: "Omnic",
    occupation: ["Multirole adaptive robot"],
    base: ["Switzerland (formerly)", "United States (formerly)", "Watchpoint: Gibraltar"],
    affiliation: ["Overwatch"],
    relations: ["Mina Liao (creator)"],
    voice: "Jeannie Bolet (English)",
    quotes: ["I am always ready to learn!"]
  },
  {
    name: "Freja",
    realName: "Freja Skov",
    aliases: ["Gefn"],
    type: "damage",
    counters: {
      Ana: "-",
      Ashe: "+*",
      Dva: "-",
      Genji: "-",
      Orisa: "+*",
      Sigma: "-*",
      Sombra: "-",
      Symmetra: "+",
      Torbjorn: "++",
      // Tracer: "-*",
      Widowmaker: "-",
      Winston: "-",
      // WreckingBall: "+*",
      Zenyatta: "++"
    },
    archetype: ["Sniper", "Specialist"],
    difficulty: 3,
    skill: 0,
    role: "Damage",
    health: { openQueue: 225, roleQueue: 225, sixVSix: 225 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: "Active",
    birth: "September 6",
    age: 34,
    ages: { "Overwatch 2": 34 },
    nationality: "Danish",
    occupation: ["Search and rescue specialist (formerly)", "Bounty hunter"],
    base: ["Copenhagen, Denmark (formerly)", "Unknown"],
    affiliation: ["Danish Armed Forces (formerly)", "Overwatch Search and Rescue (formerly)"],
    voice: "Olivia Le Andersen (English)",
    quotes: ["I always deliver."]
  },
  {
    name: "Genji",
    realName: "Genji Shimada (島田 源氏)",
    aliases: ["Sparrow"],
    type: "damage",
    counters: {
      Ana: "-",
      Baptiste: "+",
      Bastion: "+",
      Brigitte: "-",
      Freja: "+",
      Hanzo: "++",
      Mercy: "++",
      Pharah: "-",
      Soldier76: "+",
      Tracer: "+", 
      Venture: "-",
      Widowmaker: "++",
      Winston: "--",
      Zarya: "--",
      Zenyatta: "+"
    },
    archetype: ["Flanker", "Scrapper"],
    difficulty: 3,
    skill: 3,
    role: "Damage",
    health: { openQueue: 250, roleQueue: 250, sixVSix: 250 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: null,
    birth: "October 28",
    age: 37,
    ages: { Overwatch: 35, "Overwatch 2": 37 },
    nationality: "Japanese",
    occupation: ["Adventurer", "Samurai"],
    base: ["Hanamura, Japan (formerly)", "Shambali Monastery, Nepal (formerly)", "Watchpoint: Gibraltar"],
    affiliation: ["Shimada Clan (formerly)", "Blackwatch (formerly)", "Overwatch (left, later rejoined)", "Shambali (temporarily)"],
    relations: ["Hanzo Shimada (older brother)", "Sojiro Shimada (father)", "Rumiko Shimada (mother)"],
    voice: "Gaku Space (English)",
    quotes: ["Peace returns to those that wish for it."]
  },
  {
    name: "Hanzo",
    realName: "Hanzo Shimada (島田 半蔵)",
    type: "damage",
    counters: {
      Ashe: "+",
      Bastion: "+",
      Dva: "-",
      Genji: "--",
      Orissa: "+",
      Sombra: "+",
      Torbjorn: "++",
      Tracer: "-",
      Widowmaker: "-",
      Winston: "--"
    },
    archetype: ["Anchor", "Sniper"],
    difficulty: 3,
    skill: 3,
    role: "Damage",
    health: { openQueue: 250, roleQueue: 250, sixVSix: 250 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: null,
    birth: "November 3",
    age: 40,
    ages: { Overwatch: 38, "Overwatch 2": 40 },
    nationality: "Japanese",
    occupation: ["Assassin", "Mercenary (temporary)"],
    base: ["Hanamura, Japan (formerly)", "Kanazaka, Japan"],
    affiliation: ["Shimada Clan (formerly)"],
    relations: ["Sojiro Shimada (father)", "Rumiko Shimada (mother)", "Genji Shimada (younger brother)"],
    voice: "Paul Nakauchi (English)",
    quotes: ["Honor is all I have left."]
  },
  {
    name: "Junkrat",
    realName: "Jamison Fawkes",
    aliases: [],
    type: "damage",
    counters: {
      Ashe: "-",
      Bastion: "+",
      Brigitte: "+",
      Dva: "+",
      Echo: "--",
      Kiriko: "-",
      Orisa: "+",
      Pharah: "--",
      Reaper: "+",
      Reinhardt: "++",
      Sombra: "+",
      Torbjorn: "++",
      Tracer: "+",
      Widowmaker: "--",
      Zarya: "-"
    },
    archetype: ["Anchor", "Flanker", "Scrapper"],
    difficulty: 2,
    skill: 2,
    role: "Damage",
    health: { openQueue: 250, roleQueue: 250, sixVSix: 250 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: null,
    birth: "February 29",
    age: 27,
    ages: { "Overwatch 2": 27 },
    nationality: "Australian",
    occupation: ["Anarchist", "Thief", "Demolitionist", "Mercenary", "Scavenger"],
    base: ["Junkertown, Australia (formerly)"],
    affiliation: ["Junkers (formerly)"],
    relations: [],
    voice: "Chris Parson (English)",
    quotes: ["Plenty of bombs to go around!"]
  },
  {
    name: "Mei",
    realName: "Mei-Ling Zhou (周美灵)",
    aliases: [],
    type: "damage",
    counters: {
      Ashe: "-",
      Dva: "+",
      Doomfist: "+",
      JunkerQueen: "++",
      Lucio: "-",
      Mauga: "+",
      Cassidy: "+",
      Pharah: "-",
      Reinhardt: "++",
      Roadhog: "++",
      Widowmaker: "-",
      WreckingBall: "+",
      Zarya: "-"
    },
    archetype: ["Scrapper", "Specialist"],
    difficulty: 3,
    skill: 3,
    role: "Damage",
    health: { openQueue: 300, roleQueue: 300, sixVSix: 300 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: null,
    birth: "September 5",
    age: 33,
    ages: { biological: 33, chronological: 42 },
    nationality: "Chinese",
    occupation: ["Climatologist", "Adventurer"],
    base: ["Xi'an, China (formerly)"],
    affiliation: ["Overwatch", "Atlas News"],
    voice: "Elise Zhang (English and Chinese Mandarin)",
    quotes: ["Come on, Snowball! They need our help!"]
  },
  {
    name: "Pharah",
    realName: "Fareeha Amari (فريحة عماري)",
    aliases: ["Fareeha English (original name)"],
    type: "damage",
    counters: {
      Ana: "-",
      Ashe: "-",
      Brigitte: "++",
      Dva: "-",
      Doomfist: "++",
      Genji: "+",
      Junkrat: "++",
      Ilari: "-",
      Lucio: "++",
      Cassidy: "--",
      Mei: "+",
      Reaper: "++",
      Reinhardt: "++",
      Sojourn: "-",
      Soldier76: "--",
      Symmetra: "++",
      Torbjorn: "+",
      Tracer: "+",
      Venture: "++", // new
      Widowmaker: "--",
      Zarya: "++"
    },
    archetype: ["Anchor", "Flanker", "Specialist"],
    difficulty: 1,
    skill: 1,
    role: "Damage",
    health: { openQueue: 225, roleQueue: 225, sixVSix: 225 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: null,
    birth: "April 15",
    age: 34,
    ages: { Overwatch: 32, "Overwatch 2": 34 },
    nationality: "Canadian/Egyptian",
    occupation: ["Security chief"],
    base: ["Cairo, Egypt (formerly)", "Giza, Egypt (formerly)", "Watchpoint: Gibraltar"],
    affiliation: ["Egyptian Army (formerly)", "Helix Security International (formerly)", "Overwatch"],
    relations: ["Ana Amari (mother)", "Sam English (father)"],
    voice: "Jen Cohn (English)",
    quotes: ["Strike from above."]
  },
  {
    name: "Reaper",
    realName: "Gabriel Reyes",
    aliases: ["Smokey (nickname)"],
    type: "damage",
    counters: {
      Ana: "-",
      Doomfist: "+",
      Dva: "-",
      Echo: "-",
      Junkrat: "-",
      JunkerQueen: "+",
      Orisa: "+",
      Pharah: "--",
      Reinhardt: "++",
      Roadhog: "++",
      Sombra: "+",
      Winston: "++",
      WreckingBall: "+",
      Zarya: "+"
    },
    archetype: ["Flanker", "Scrapper"],
    difficulty: 1,
    skill: 1,
    role: "Damage",
    health: { openQueue: 300, roleQueue: 300, sixVSix: 300 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: null,
    birth: "December 14",
    age: 60,
    ages: { Overwatch: 58, "Overwatch 2": 60 },
    nationality: "American",
    occupation: ["Police officer (formerly)", "Soldier (formerly)", "Strike commander (formerly)", "Blackwatch commander (formerly)", "Talon Field agent/council member"],
    base: ["Los Angeles, United States (formerly)", "Rome, Italy"],
    affiliation: ["Los Angeles Police Department (formerly)", "United States Army (formerly)", "Soldier Enhancement Program (formerly)", "Overwatch (formerly)", "Blackwatch (formerly)", "Talon"],
    relations: ["Martina Reyes (wife)", "Unnamed son"],
    voice: "Keith Ferguson (English)",
    quotes: ["You can't escape death."]
  },
  {
    name: "Sojourn",
    realName: "Vivian Chase",
    type: "damage",
    counters: {
      Echo: "+",
      Mercy: "-",
      Pharah: "+",
      Winston: "-",
      Zarya: "-"
    },
    archetype: ["Anchor", "Flanker", "Sniper"],
    difficulty: 0,
    skill: 0,
    role: "Damage",
    health: { openQueue: 225, roleQueue: 225, sixVSix: 225 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: "Active",
    birth: "January 12",
    age: 51,
    ages: { "Overwatch 2": 51 },
    nationality: "Canadian",
    occupation: ["Infantrywoman (formerly)", "Special Forces operative (formerly)", "Overwatch captain (formerly)", "Acting commander (formerly)"],
    base: ["Toronto, Canada"],
    affiliation: ["Primary Reserve (formerly)", "Canadian Army (formerly)", "Canadian Special Operations Regiment (formerly)", "Overwatch"],
    relations: ["Unnamed grandmother", "Unnamed grandfather", "Unnamed father", "Unnamed mother", "Valentine Chase-Chapman (twin sister)", "Bonnie Chase-Chapman (niece)"],
    voice: "Cherise Boothe (English)",
    quotes: ["We're in this together. All of us."]
  },
  {
    name: "Soldier: 76",
    realName: "John Francis \"Jack\" Morrison",
    type: "damage",
    counters: {
      Baptiste: "+",
      Bastion: "+",
      Doomfist: "+",
      Echo: "+",
      Genji: "-",
      Pharah: "++",
      Reinhardt: "-",
      Sigma: "-",
      Torbjorn: "+",
      Winston: "-"
    },
    archetype: ["Anchor"],
    difficulty: 1,
    skill: 1,
    role: "Damage",
    health: { openQueue: 250, roleQueue: 250, sixVSix: 250 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: "Active",
    birth: "January 27",
    age: 58,
    ages: { Overwatch: 56, "Overwatch 2": 58 },
    nationality: "American",
    occupation: ["Soldier (formerly)", "Overwatch commander (formerly)", "Vigilante"],
    base: ["Bloomington, Indiana, United States (birth place) (formerly)", "Overwatch HQ (formerly)", "Unknown"],
    affiliation: ["United States Army (formerly)", "Soldier Enhancement Program (formerly)", "Overwatch (formerly)"],
    relations: ["Various family members, including a great-aunt, grandfather, uncle, father, and mother", "Vincent (former friend)"],
    voice: "Fred Tatasciore (English)",
    quotes: ["Every soldier needs a cause."]
  },
  {
    name: "Sombra",
    realName: "Olivia Colomar",
    type: "damage",
    counters: {
      Ana: "+",
      Bastion: "+",
      Brigitte: "+",
      Dva: "+",
      Doomfist: "++",
      Echo: "+",
      Freja: "+",
      Hanzo: "-",
      Hazard: "+",
      Junkrat: "-",
      Ilari: "+",
      Kiriko: "-",
      Lucio: "+",
      Reaper: "-",
      Reinhardt: "+",
      Roadhog: "-",
      Symmetra: "+",
      Widowmaker: "+",
      WreckingBall: "++",
      Zarya: "+",
      Zenyatta: "+"
    },
    archetype: ["Flanker", "Specialist"],
    difficulty: 3,
    skill: 3,
    role: "Damage",
    health: { openQueue: 225, roleQueue: 225, sixVSix: 225 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: "Alive",
    birth: "December 31",
    age: 32,
    ages: { Overwatch: 30, "Overwatch 2": 32 },
    nationality: "Mexican",
    occupation: ["Hacker"],
    base: ["Dorado, Mexico"],
    affiliation: ["Los Muertos (formerly)", "Talon (currently)"],
    voice: "Carolina Ravassa (English)",
    quotes: ["In my world, there are no secrets."]
  },
  {
    name: "Symmetra",
    realName: "Satya Vaswani (सत्य वासवानी)",
    type: "damage",
    counters: {
      Cassidy: "-",
      Dva: "+",
      Freja: "-", 
      Pharah: "--",
      Sombra: "-",
      Winston: "--",
      Zarya: "-"
    },
    archetype: ["Specialist"],
    difficulty: 2,
    skill: 2,
    role: "Damage",
    health: { openQueue: 125, roleQueue: 125, sixVSix: 125 },
    armor: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    shields: { openQueue: 125, roleQueue: 125, sixVSix: 125 },
    status: null,
    birth: "October 2",
    age: 30,
    ages: { Overwatch: 28, "Overwatch 2": 30 },
    nationality: "Indian",
    occupation: ["Architech"],
    base: ["Utopaea, India"],
    affiliation: ["Vishkar Corporation"],
    voice: "Anjali Bhimani (English)",
    quotes: ["From imperfection, we build a new world."]
  },
  {
    name: "Torbjorn", //"Torbjörn",
    realName: "Torbjörn Lindholm",
    type: "damage",
    counters: {
      Ana: "-",
      Echo: "-",
      Freja: "--",
      Genji: "+",
      Hanzo: "--",
      Junkrat: "-",
      Lucio: "+",
      Orisa: "-",
      Pharah: "-",
      Soldier: "-",
      Tracer: "++",
      Venture: "+",  
      Widowmaker: "--",
      WreckingBall: "+",
      Zarya: "--"
    },
    archetype: ["Anchor", "Scrapper", "Specialist"],
    difficulty: 2,
    skill: 2,
    role: "Damage",
    health: { openQueue: 225  , roleQueue: 225, sixVSix: 225 },
    armor: { openQueue: 75, roleQueue: 75, sixVSix: 75 },
    shields: { openQueue: 0, roleQueue: 0, sixVSix: 0 },
    status: null,
    birth: "September 21",
    age: 59,
    ages: { Overwatch: 57, "Overwatch 2": 59 },
    nationality: "Swedish",
    occupation: ["Weapons designer", "Chief engineer (formerly)"],
    base: ["Gothenburg, Sweden"],
    affiliation: ["Overwatch (formerly)", "Lindholm Workshop"],
    relations: [
      "Ingrid Lindholm (wife)",
      "Brigitte Lindholm (daughter)",
      "8 other daughters (unnamed)",
      "1 son (unnamed)",
      "Reinhardt Wilhelm (close friend)",
      "Angela Ziegler (colleague)",
      "Bastion (close friend)"
    ],
    voice: "Keith Silverstein (English)",
    quotes: ["Tools in hand, brain in gear."]
  },
  {
    name: "Tracer",
    type: "damage",
    counters: {
      Bastion: "+",
      Brigitte: "-",
      Cassidy: "-",
      // Freja: "+*"
      Genji: "-", // new
      Hanzo: "+",
      Junkrat: "-",
      Kiriko: "+",
      Pharah: "-",
      Torbjorn: "--",
      Venture: "--", // new
      Zenyatta: "++"
    },
    archetype: ["Flanker", "Scrapper"],
    difficulty: 2,
    skill: 2,
    health: 175,
    armor: 0,
    shields: 0,
  },
  {
    name: "Venture",
    type: "damage",
    counters: {
      Baptiste: "+",
      Brigitte: "+",  
      Echo: "--", // new
      Genji: "+", // new
      Ilari: "+", // new
      Tracer: "++", 
      Cassidy: "-", 
      Pharah: "--", 
      Sigma: "-*", // new
      //Sombra: "-*",
      Torbjorn: "-", 
      //Widowmaker: "-*", 
      Zenyatta: "+", 
    },
    archetype: ["Specialist"],
    difficulty: 0,
    skill: 0,
    health: 250,
    armor: 0,
    shields: 0,
  },
  {
    name: "Widowmaker",
    type: "damage",
    counters: {
      Ana: "+",
      Ashe: "+",
      Bastion: "+",
      Dva: "--",
      Echo: "+",
      Freja: "+",
      Genji: "--",
      Hanzo: "-",
      Junkrat: "++",
      Kiriko: "+",
      Cassidy: "+",
      Mei: "+",
      Mercy: "+",
      Orisa: "+",
      Pharah: "++",
      Reinhardt: "-",
      Sigma: "-",
      Sojourn: "-",
      Sombra: "-",
      Torbjorn: "+",
      Winston: "--",
      WreckingBall: "-"
    },
    archetype: ["Sniper"],
    difficulty: 2,
    skill: 2,
    health: 200,
    armor: 0,
    shields: 0,
  },
  {
    name: "Ana",
    type: "support",
    counters: {
      Ashe: "+",
      Baptiste: "+",
      Bastion: "+",
      Dva: "-",
      Echo: "+",
      Freja: "+",
      Genji: "+",
      JunkerQueen: "-",
      Ilari: "+",
      Kiriko: "-",
      Lucio: "+",
      Mauga: "+",
      Moira: "+",
      Pharah: "+",
      Reaper: "+",
      Roadhog: "++",
      Sigma: "-",
      Sombra: "-",
      Widowmaker: "-",
      Winston: "-",
      WreckingBall: "+",
      Zenyatta: "+"
    },
    archetype: ["Main Healer", "Utility"],
    difficulty: 3,
    skill: 3,
    health: 250,
    armor: 0,
    shields: 0,
  },
  {
    name: "Baptiste",
    type: "support",
    counters: {
      Ana: "-",
      Doomfist: "+",
      Dva: "+",
      Echo: "+",
      Genji: "-",
      Roadhog: "+",
      Sombra: "-",
      Soldier: "-"
    },
    archetype: ["Main Healer", "Utility"],
    difficulty: 3,
    skill: 3,
    health: 250,
    armor: 0,
    shields: 0,
  },
  {
    name: "Brigitte",
    type: "support",
    counters: {
      Ashe: "-",
      Bastion: "-", 
      Dva: "+",
      Genji: "+",
      Junkrat: "-",
      Pharah: "--",
      Reaper: "-",
      Reinhardt: "+",
      Sombra: "-",
      Tracer: "+",
      Venture: "-",
      WreckingBall: "+"
    },
    archetype: ["Pocket Healer", "Utility"],
    difficulty: 1,
    skill: 1,
    health: 150,
    armor: 50,
    shields: 0,
  },
  {
    name: "Ilari",
    type: "support",
    counters: {
      Ana: "-",
      Dva: "-",
      // Echo: "-*",
      Pharah: "+",
      Sombra: "-",
      Venture: "-",
    },
    archetype: ["Utility"],
    difficulty: 0,
    skill: 0,
    health: 250,
    armor: 0,
    shields: 0,
  },
  {
    name: "Juno",
    type: "support",
    counters: {
      Pharah: "+",
      Echo: "+",
      ashe: "-",
      Dva: "--*",
      Tracer: "-*",
      Winston: "-",
    },
    archetype: ["Utility"],
    difficulty: 0,
    skill: 0,
    health: 75,
    armor: 0,
    shields: 150,
  },
  {
    name: "Kiriko",
    type: "support",
    counters: {
      Ana: "+",
      Junkrat: "+",
      Ramattra: "+",
      Sombra: "+",
      Tracer: "-",
      Widowmaker: "-"
    },
    archetype: ["Utility"],
    difficulty: 0,
    skill: 0,
    health: 200,
    armor: 0,
    shields: 0,
  },
  {
    name: "Lifeweaver",
    type: "support",
    counters: {
      Ana: "-",
      Bastion: "-",
      Echo: "-",
      Genji: "-",
      Junkrat: "-",
      JunkerQueen: "-",
      Lucio: "-",
      Mei: "-",
      Mercy: "-",
      Pharah: "-",
      Reaper: "-",
      Reinhardt: "-",
    },
    archetype: ["Main Healer", "Utility"],
    difficulty: 0,
    skill: 0,
    health: 250,
    armor: 0,
    shields: 0,
  },
  {
    name: "Lucio",
    type: "support",
    counters: {
      Ashe: "-",
      Bastion: "-",
      Cassidy: "--",
      Mei: "+",
      Roadhog: "-",
      Pharah: "--",
      Sigma: "+",
      Sombra: "-",
      Torbjorn: "-",
      WreckingBall: "+"
    },
    archetype: ["Utility"],
    difficulty: 2,
    skill: 2,
    health: 200,
    armor: 0,
    shields: 0,
  },
  {
    name: "Mercy",
    type: "support",
    counters: {
      Ana: "-",
      Ashe: "-",
      Dva: "--",
      Genji: "--",
      Cassidy: "-",
      Roadhog: "-",
      Sojourn: "-",
      Widowmaker: "-"
    },
    archetype: ["Pocket Healer"],
    difficulty: 1,
    skill: 1,
    health: 200,
    armor: 0,
    shields: 0,
  },
  {
    name: "Moira",
    type: "support",
    counters: {
      Ana: "-",
      Dva: "-",
      Orisa: "+",
      Reinhardt: "+",
      WreckingBall: "-"
    },
    archetype: ["Main Healer"],
    difficulty: 2,
    skill: 2,
    health: 200,
    armor: 0,
    shields: 0,
  },
  {
    name: "Wuyang",
    realName: "Wuyang Ye (叶无漾)",
    type: "support",
    counters: {
      Ana: "-*",
      Genji: "-*",
      Sombra: "-*",
      Widowmaker: "-*",
    },
    archetype: ["Pocket Healer"],
    difficulty: 0,
    skill: 0,
    health: 250,
    shields: 0,

    status: "active",
    birth: "May first",
    age: 19,
    occupation: "First-year student",
    base: 'Water College (Wuxing U), Chengdu, Sichuan, China',
    affiliation: 'Wuxing University Overwatch',
    relations: ['Unnamed parents', 'Anran Ye (older sister)'],
    voice: ['Howard Wang (English)']
  },
  {
    name: "Zenyatta",
    type: "support",
    counters: {
      Ana: "-",
      Freja: "--",
      Genji: "-",
      JunkerQueen: "+",
      Orisa: "+",
      Ramattra: "+",
      Reinhardt: "+", 
      Sombra: "-",
      Tracer: "--",
      Venture: "-*", // new
      Zarya: "+"
    },
    archetype: ["Pocket Healer", "Utility"],
    difficulty: 3,
    skill: 3,
    health: 50,
    armor: 0,
    shields: 150,
  }
];

exports.heroData = heroData;